### ISSUE TITLE
课程分好几集，第一集视频100%但是视频没有看完，不会自动下一集

### ISSUE THREAD

**Issue by hanjiangjiaolong** [xinyunaha/enaeaHelper#3]

**Comment by xinyunaha** [comment]
能否留个联系方式加个好友看看呢？我加的课没出现这种问题，可能课程类型有点不一样

**Comment by hanjiangjiaolong** [comment]
给朋友帮忙整的，我没账号。
他的现象就是一个视频32分钟，看8分钟就算这个进度100%了，理论上这个时候插件应该检测到100%。自动跳下一个视频，但是没有

**Comment by xinyunaha** [comment]
> 给朋友帮忙整的，我没账号。 他的现象就是一个视频32分钟，看8分钟就算这个进度100%了，理论上这个时候插件应该检测到100%。自动跳下一个视频，但是没有

实际上判断100%是通过进度条来的，因为我在这平台所遇见的课程都是需要观看满一定时间的
